# Generated by Django 4.1.2 on 2022-10-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='freelance',
            field=models.CharField(choices=[('true', 'Avialable'), ('false', 'Not Avialable')], default='Avialable', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
