# Generated by Django 4.1.2 on 2022-10-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_profile_freelance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('sub_titel', models.CharField(max_length=32)),
                ('emoji', models.CharField(max_length=50)),
                ('volume', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
