# Generated by Django 4.1.2 on 2022-10-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_skill_alter_profile_freelance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('grade', models.CharField(max_length=100)),
                ('field_study', models.CharField(max_length=200)),
                ('started_year', models.DateField(blank=True, null=True)),
                ('ended_year', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='freelance',
            field=models.CharField(choices=[('Available', 'true'), ('Not Available', 'false')], default='true', max_length=20),
        ),
    ]
