# Generated by Django 4.1.2 on 2022-10-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_education_alter_profile_freelance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_address', models.CharField(max_length=255)),
                ('current_coutnry', models.CharField(max_length=100)),
                ('current_city', models.CharField(max_length=155)),
                ('home_country', models.CharField(max_length=100)),
                ('home_city', models.CharField(max_length=100)),
                ('home_address', models.CharField(max_length=100)),
            ],
        ),
    ]
