# Generated by Django 4.1.2 on 2022-10-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('employement_type', models.CharField(choices=[('Contract', 'CONTRACT'), ('Part Time', 'PART_TIME'), ('Temprary', 'TEMPRIRY'), ('Intrenship', 'INTRENSHIP'), ('Freelance', 'FREELANCE'), ('Full Time', 'FULL_TIME'), ('Self Employed', 'SELF_EMPLOYED')], max_length=200)),
                ('company_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('industry', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
