# Generated by Django 4.1.2 on 2022-10-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_experience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-start_date']},
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='MOH KHALID', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='MOMAND', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='summary',
            field=models.TextField(default='NONE'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='employement_type',
            field=models.CharField(choices=[('Contract', 'CONTRACT'), ('Temprary', 'TEMPRIRY'), ('Part Time', 'PART_TIME'), ('Intrenship', 'INTRENSHIP'), ('Full Time', 'FULL_TIME'), ('Freelance', 'FREELANCE'), ('Self Employed', 'SELF_EMPLOYED')], max_length=200),
        ),
    ]
