# Generated by Django 4.1.2 on 2022-10-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_experience_options_profile_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed')], default='In Progress', max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='experience',
            name='employement_type',
            field=models.CharField(choices=[('Temprary', 'TEMPRIRY'), ('Intrenship', 'INTRENSHIP'), ('Contract', 'CONTRACT'), ('Freelance', 'FREELANCE'), ('Self Employed', 'SELF_EMPLOYED'), ('Full Time', 'FULL_TIME'), ('Part Time', 'PART_TIME')], max_length=200),
        ),
    ]
