# Generated by Django 4.1.2 on 2022-10-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_courses_alter_experience_employement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='organized',
            field=models.CharField(default='codewithmosh.com', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='employement_type',
            field=models.CharField(choices=[('Intrenship', 'INTRENSHIP'), ('Temprary', 'TEMPRIRY'), ('Contract', 'CONTRACT'), ('Full Time', 'FULL_TIME'), ('Part Time', 'PART_TIME'), ('Freelance', 'FREELANCE'), ('Self Employed', 'SELF_EMPLOYED')], max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='freelance',
            field=models.CharField(choices=[('Not Available', 'false'), ('Available', 'true')], default='true', max_length=20),
        ),
    ]
