# Generated by Django 4.1.2 on 2022-10-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_courses_organized_alter_experience_employement_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='end_date',
            new_name='expiry_date',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='start_date',
            new_name='issued_date',
        ),
        migrations.AlterField(
            model_name='courses',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In Progress', 'In Progress')], default='In Progress', max_length=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='employement_type',
            field=models.CharField(choices=[('Full Time', 'FULL_TIME'), ('Freelance', 'FREELANCE'), ('Contract', 'CONTRACT'), ('Temprary', 'TEMPRIRY'), ('Self Employed', 'SELF_EMPLOYED'), ('Part Time', 'PART_TIME'), ('Intrenship', 'INTRENSHIP')], max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='freelance',
            field=models.CharField(choices=[('Available', 'true'), ('Not Available', 'false')], default='true', max_length=20),
        ),
    ]
