# Generated by Django 4.1.2 on 2022-10-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_rename_end_date_courses_expiry_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('In Progress', 'In Progress')], default='Completed', max_length=100)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('organized', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-ended_year']},
        ),
        migrations.AlterField(
            model_name='experience',
            name='employement_type',
            field=models.CharField(choices=[('Contract', 'CONTRACT'), ('Intrenship', 'INTRENSHIP'), ('Temprary', 'TEMPRIRY'), ('Self Employed', 'SELF_EMPLOYED'), ('Full Time', 'FULL_TIME'), ('Freelance', 'FREELANCE'), ('Part Time', 'PART_TIME')], max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='freelance',
            field=models.CharField(choices=[('Not Available', 'false'), ('Available', 'true')], default='true', max_length=20),
        ),
    ]
