# Generated by Django 4.1.2 on 2022-10-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_certificates_delete_courses_alter_education_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='certificates',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Completed', max_length=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='employement_type',
            field=models.CharField(choices=[('Self Employed', 'SELF_EMPLOYED'), ('Freelance', 'FREELANCE'), ('Contract', 'CONTRACT'), ('Part Time', 'PART_TIME'), ('Full Time', 'FULL_TIME'), ('Temprary', 'TEMPRIRY'), ('Intrenship', 'INTRENSHIP')], max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='freelance',
            field=models.CharField(choices=[('Available', 'true'), ('Not Available', 'false')], default='true', max_length=20),
        ),
    ]
